### ISSUE TITLE
Add new model

### ISSUE THREAD

**Issue by TamasMatuszka** [chaytonmin/Awesome-BEV-Perception-Multi-Cameras#6]
Hi chaytonmin!

I'd like to contribute to your awesome repository but I'm not allowed to create a new branch and a pull request from it. Could you tell me how can I add new lines to the README.md? Thank you.

**Comment by chaytonmin** [comment]
> Hi chaytonmin!
> 
> I'd like to contribute to your awesome repository but I'm not allowed to create a new branch and a pull request from it. Could you tell me how can I add new lines to the README.md? Thank you.

You can create a pull request.
Or you can add the new README.md here, and I will add them to the repository.

**Comment by TamasMatuszka** [comment]
Thank you for your answer!

I have some troubles with the pull request. Therefore, I add the new README.md here.

Thanks again!
[README.md](https://github.com/chaytonmin/Awesome-BEV-Perception-Multi-Cameras/files/10105495/README.md)
